### PR TITLE
Remove configure property

### PR DESCRIPTION
**Pull request by andreasohlund**
Needs https://github.com/Particular/NServiceBus/pull/3467 to be merged first

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/container-maintainers I need help with the failing acceptance test? (is property injection for Spring really broken?) 

https://builds.particular.net/viewLog.html?buildId=155100&buildTypeId=NServiceBus_Containers_NServiceBusSpring_2AcceptanceTests

**Comment by boblangley** [comment]
@andreasohlund I fixed the test. I spot checked core and couldn't find any examples, but we don't mix constructor injection / property injection correct?

**Comment by andreasohlund** [comment]
>but we don't mix constructor injection / property injection correct?

Pretty sure we don't, but we have no tests to verify.

I have an evil plan to turn prop injection off by default in vNext (to pave the way for us not supporting it ootb)

Is this one good to go then?

**Comment by boblangley** [comment]
@andreasohlund I believe so.

**Comment by andreasohlund** [comment]
My bad, hadn't removed the code, should be good for final review now

**Comment by boblangley** [comment]
Merged #18

**Pull request merged**
