### PR TITLE
Update to beta6

### PR DESCRIPTION
**Pull request by WilliamBZA**
Update the container to Beta6

Ping @Particular/container-maintainers

### CODE REVIEW

**Comment by danielmarbach** [comment]
seems to fail

**Comment by WilliamBZA** [comment]
`//Not supported by,typeof(SpringObjectBuilder));`

:smile:

**Comment by danielmarbach** [comment]
So we just let it fail then (sorry don't remember how we did this in the past)?

**Comment by WilliamBZA** [comment]
Yeah, we just let it fail. Which raises the question of what the tests are actually testing. If the tests fail, and it doesn't matter, why do we have the tests?

Conversely, if the tests do matter, why did we ignore them for Spring in the past? Perhaps core doesn't require these methods from the container.

**Comment by danielmarbach** [comment]
Maybe the approach should be to have a better way to skip tests, features that are not supported.

**Comment by WilliamBZA** [comment]
I'm not sure. Why do we have the tests if we can just ignore them?

**Comment by danielmarbach** [comment]
Typical conforming container problem. The conforming container defines the
feature set. Not all container can fulfill it. And yes the answer should be
to move away from conforming containers *sigh*

**Pull request merged**
