### PR TITLE
Updating to core 1751

### PR DESCRIPTION
**Pull request by andreasohlund**
@Particular/nservicebus-maintainers preparing for https://github.com/Particular/NServiceBus/pull/3467 I updated to latest core on myget. This caused a bunch of unittests to fail. Can someone help me sort them out?

### CODE REVIEW

**Comment by andreasohlund** [comment]
2 of them seems to have been disabled before but 3 of them is new failures due to updates to the container test suite

**Comment by andreasohlund** [comment]
Thanks @boblangley !

@Particular/container-maintainers I'll remove .ConfigureProperty once this one is pulled

**Comment by HEskandari** [comment]
@boblangley could you look at the failed build? I can merge that once the build is green.

**Comment by boblangley** [comment]
@HEskandari Light is green, trap is clean.

**Pull request merged**
